title: P25 DVM
description: This repository will be the base of the unofficial troubleshooting and setup guides for use with the DVMProject. All information contained has been contributed by community members and is no way affiliated with the DVMProject.
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
