site_name: The Unofficial DVMProject P25 Knowledge Base
site_description: A community operated knowledge base regarding P25 operations while utilizing the DVMProject.
site_url: https://p25-dvm.github.io
repo_url: https://github.com/p25-dvm/
repo_name: P25 DVM

theme:
  name: readthedocs
  font:
    text: Share Tech Mono
    code: Share Tech Mono
  palette:
    scheme: slate
    primary: black
    accent: light green
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Getting Started:
      - Hardware: hardware/hardware.md
  - Hotspots:
      - Conventional Hotspot: conventional-hotspot/conventional-hotspot.md
      - Trunking Hotspot: trunking-hotspot/trunking-hotspot.md
  - Traditional RF Site:
      - Motorola CDM1250 Site: traditional-rf-site/motorola-cdm1250-site.md
  - Reference:
      - Frequently Asked Questions: reference/faq.md
      - Common Errors: reference/common-errors.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: false

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/<your-github-username>/<your-repo-name>
